#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import importlib.util
from pathlib import Path
import tempfile
import unittest
import zipfile

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location("moonraker_gcode_3mf", HERE / "moonraker_gcode_3mf.py")
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)
GCode3MF = MODULE.GCode3MF


class FakeFileManager:
    def __init__(self, root: Path):
        self.root = root

    def get_directory(self, name: str) -> str:
        assert name == "gcodes"
        return str(self.root)


def make_component(root: Path):
    component = object.__new__(GCode3MF)
    component.file_manager = FakeFileManager(root)
    component.cache_subdir = ".zmod/gcode_3mf"
    component.source_archive_subdir = ".zmod/gcode_3mf/source"
    return component


def write_3mf(path: Path, gcode: bytes, plate: int = 1) -> str:
    digest = hashlib.md5(gcode).hexdigest()
    member = f"Metadata/plate_{plate}.gcode"
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(member, gcode)
        zf.writestr(member + ".md5", digest)
    return digest


class VisibleJobLifecycleTests(unittest.TestCase):
    def test_extracts_human_visible_gcode_and_archives_source(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            source = root / "Phone Stand.gcode.3mf"
            payload = b"; generated by OrcaSlicer\nG28\nG1 X10 Y10\n"
            digest = write_3mf(source, payload)
            comp = make_component(root)

            prepared = comp._prepare_sync(source.name)

            self.assertEqual(prepared["gcode_relative"], "Phone Stand.gcode")
            self.assertFalse(prepared["visible_reused"])
            self.assertEqual((root / prepared["gcode_relative"]).read_bytes(), payload)
            self.assertTrue(source.is_file(), "source must remain until print start succeeds")

            archived = comp._archive_source_sync(source.name, digest)
            self.assertFalse(source.exists())
            self.assertEqual(
                archived,
                f".zmod/gcode_3mf/source/{digest[:12]}/Phone Stand.gcode.3mf",
            )
            self.assertTrue((root / archived).is_file())

    def test_reuses_same_content_without_rewriting_visible_file(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            source = root / "Widget.gcode.3mf"
            payload = b"G28\nM84\n"
            comp = make_component(root)

            write_3mf(source, payload)
            first = comp._prepare_sync(source.name)
            visible = root / first["gcode_relative"]
            first_mtime = visible.stat().st_mtime_ns

            source.unlink()
            write_3mf(source, payload)
            second = comp._prepare_sync(source.name)

            self.assertEqual(second["gcode_relative"], "Widget.gcode")
            self.assertTrue(second["visible_reused"])
            self.assertEqual(visible.stat().st_mtime_ns, first_mtime)

    def test_collision_preserves_old_slice_and_uses_content_suffix(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            source = root / "Widget.gcode.3mf"
            comp = make_component(root)

            write_3mf(source, b"G28\nOLD\n")
            first = comp._prepare_sync(source.name)
            self.assertEqual(first["gcode_relative"], "Widget.gcode")

            source.unlink()
            digest = write_3mf(source, b"G28\nNEW\n")
            second = comp._prepare_sync(source.name)

            self.assertEqual(
                second["gcode_relative"], f"Widget-{digest[:8]}.gcode"
            )
            self.assertEqual((root / "Widget.gcode").read_bytes(), b"G28\nOLD\n")
            self.assertEqual(
                (root / second["gcode_relative"]).read_bytes(), b"G28\nNEW\n"
            )

    def test_non_primary_plate_gets_explicit_plate_suffix(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            source = root / "Multi.gcode.3mf"
            comp = make_component(root)
            # Current production path rejects multi-plate containers, but the
            # naming helper is future-proof for an explicitly selected plate.
            self.assertEqual(comp._visible_name(source, 2), "Multi-plate2.gcode")


if __name__ == "__main__":
    unittest.main()
